service: alexa-givennames-skill

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  timeout: 8
  memorySize: 256

package:
  individually: true
  exclude:
    - '**'

functions:
  skill:
    handler: build/skill.handler
    package:
      include:
        - build/skill*
    events:
      - alexaSkill
